"""Facts for each generated tool page. Checked against the Workblox apps on
2026-10-01 -- if a tool changes (inputs, outputs, file types, limits,
storage), update its entry here and re-run build_tool_pages.py.

Text is HTML: use &mdash;, &amp; and friends. Never claim popularity,
reviews or results nobody measured, and never say "your team" (Business is
single-user).
"""

# Shared wording, so every page says the same thing the same way.
TOOLBAR = "Download it as a PDF, TXT or Markdown file, or have a PDF copy emailed to you."
PROFILE = ("Save your business name and contact details once in Settings, and they're filled in for "
           "you &mdash; no placeholders to replace by hand.")
CONTACTS = "Pick the person straight from your Workblox Contacts instead of typing their details."
STORED_WRITING = ("No. What you enter is used to write your result and isn't kept afterward. The only "
                  "things Workblox Business saves are your business profile and, if you use it, your "
                  "Contacts list. See the <a href=\"privacy.html\">Privacy Policy</a>.")
STORED_FILES = ("No. Your files are processed to produce your result and discarded &mdash; nothing is "
                "stored. See the <a href=\"privacy.html\">Privacy Policy</a>.")
REVIEW_IT = "Read it over before you send it &mdash; it's your name on it."

PAGES = [
    # ── Hiring ────────────────────────────────────────────────────────────
    {
        "slug": "interview-questions-generator.html",
        "app": "business",
        "tool": "Hiring Manager",
        "title": "Interview Questions Generator &amp; Hiring Kit for Small Business",
        "description": "Describe the job you're hiring for and get a complete hiring kit: a position summary, interview questions, what to look for, red flags and onboarding tips.",
        "h1": "Hiring someone?<br><em>Walk in prepared.</em>",
        "lead": "Describe the position in a few sentences and get a complete hiring kit &mdash; a position summary, interview questions, what a strong answer looks like, red flags to watch for, and tips for the first weeks.",
        "hero_note": "Single user, no HR department needed.",
        "outputs_heading": "A hiring kit for any position.",
        "outputs_sub": "Everything you need before, during and after the interview, in one place.",
        "outputs": [
            ("Position summary", "A clear description of the role, so you know exactly who you're looking for."),
            ("Interview questions", "Questions written for this specific position, ready to ask."),
            ("Evaluation criteria", "What a strong candidate shows, so you can compare people fairly."),
            ("Red flags to watch", "Warning signs to listen for in answers and backgrounds."),
            ("Onboarding tips", "How to get your new hire up to speed in the first weeks."),
            ("Save or send it", TOOLBAR),
        ],
        "example": {
            "heading": "From a few sentences to a hiring kit.",
            "sub": "A made-up example, shortened to three interview questions.",
            "before": "&ldquo;Part-time front counter person for our dry cleaning shop. Handles drop-offs and pickups, the register, and phone calls. Weekends required.&rdquo;",
            "after_title": "Interview questions",
            "after": [
                "Tell me about a time a customer was upset about something that wasn't your fault. What did you do?",
                "How do you keep track of details when the counter gets busy?",
                "Our busiest days are Saturdays. How does a weekend schedule fit with your other commitments?",
            ],
        },
        "steps_heading": "Three steps.",
        "steps": [
            ("Describe the position", "A few sentences about the job, the hours and what matters most."),
            ("Get your hiring kit", "The summary, questions, criteria, red flags and onboarding tips appear together."),
            ("Use it in the interview", "Print it, keep it on your phone, or email yourself a copy."),
        ],
        "callout": "<strong>Screening a pile of resumes first?</strong> The <a href=\"resume-screening-tool.html\">Batch ATS Analyzer</a> ranks up to 10 at once against your job description.",
        "faqs": [
            ("Do I need HR experience?", "No. It's built for owners and managers who hire a few times a year and want to be prepared, without an HR department."),
            ("Can I write the job posting too?", "Yes &mdash; that's the <a href=\"job-description-writer.html\">Job Description Writer</a>, another Workblox Business tool."),
            ("Is what I enter stored?", STORED_WRITING),
        ],
        "cta": "Your next interview, prepared.",
    },
    {
        "slug": "resume-screening-tool.html",
        "app": "business",
        "tool": "Batch ATS Analyzer",
        "title": "Resume Screening Tool — Rank Up to 10 Resumes Against Your Job Description",
        "description": "Upload up to 10 resumes and a job description. Every candidate gets a match score, matched and missing keywords, strengths, concerns and an Advance, Maybe or Pass recommendation.",
        "h1": "Ten resumes.<br><em>One ranked list.</em>",
        "lead": "Upload up to 10 resumes, paste your job description, and see every candidate scored and ranked &mdash; with the keywords they match, what they're missing, their strengths and concerns, and a recommendation for each.",
        "hero_note": "PDF, Word, Pages and TXT resumes. Resumes are never stored.",
        "outputs_heading": "A shortlist without reading every page.",
        "outputs_sub": "Each candidate is checked against your job description, then sorted from best match down.",
        "outputs": [
            ("Match score", "A percentage for each candidate, with a Strong, Good, Fair or Weak match level."),
            ("Ranked list", "Candidates sorted from the best match down, so you know who to read first."),
            ("Keywords matched and missing", "Which requirements from your job description each resume covers."),
            ("Strengths and concerns", "What stands out about each candidate, good and bad."),
            ("A recommendation", "Advance, Maybe or Pass for every candidate."),
            ("Hidden text check", "White or tiny text hidden in a PDF or Word resume is ignored, so it can't game the score."),
        ],
        "highlight_last": True,
        "example": None,
        "steps_heading": "Three steps.",
        "steps": [
            ("Upload resumes", "Up to 10 at once &mdash; PDF, Word (.docx), Pages or TXT."),
            ("Paste the job description", "The more detail you include, the better the matching."),
            ("Read the ranked results", "Start at the top and download or email the full report."),
        ],
        "callout": "<strong>A screening aid, not the decision.</strong> Use the ranking to decide who to read first, and make the hiring decision yourself.",
        "faqs": [
            ("How many resumes can I screen at once?", "Up to 10 per batch. Run another batch for more."),
            ("Is this the same as the ATS Analyzer in Workblox Personal?", "No. The Personal <a href=\"ats-resume-checker.html\">ATS Analyzer</a> helps a job seeker improve one resume. This tool helps an employer compare several candidates against a full job description."),
            ("Are the resumes stored?", "No. Resumes are processed to produce your results and nothing is kept afterward. See the <a href=\"privacy.html\">Privacy Policy</a>."),
        ],
        "cta": "Find your best candidates first.",
    },
    {
        "slug": "job-description-writer.html",
        "app": "business",
        "tool": "Job Description Writer",
        "title": "Job Description Writer — Create a Complete Job Posting in Minutes",
        "description": "Enter a job title and the key requirements, and get a complete job description: overview, responsibilities, requirements, nice-to-haves and benefits, ready to post.",
        "h1": "A job posting that<br><em>attracts the right people.</em>",
        "lead": "Enter the job title and what the role needs, and get a complete, professional job description &mdash; overview, responsibilities, requirements, nice-to-haves and benefits &mdash; ready to post.",
        "hero_note": "Your business details filled in automatically.",
        "outputs_heading": "Every section a job posting needs.",
        "outputs_sub": "Organized the way job boards and applicants expect.",
        "outputs": [
            ("Overview", "A short, inviting description of the role."),
            ("Responsibilities", "What the person will do day to day."),
            ("Requirements", "The skills and experience the job needs."),
            ("Nice to have", "Extras that would help, kept separate so good people still apply."),
            ("Benefits", "What you offer, including the salary range if you enter one."),
            ("Your business, filled in", PROFILE),
        ],
        "example": {
            "heading": "From a few notes to a posting.",
            "sub": "A made-up example, showing part of the responsibilities.",
            "before": "Job title: <strong>Landscaping Crew Member</strong><br>Requirements: &ldquo;mowing, trimming, mulching, valid driver's license, early starts, lift 50 lbs&rdquo;",
            "after_title": "Responsibilities",
            "after": [
                "Mow, trim and edge residential and commercial properties to a clean, consistent finish",
                "Spread mulch and keep beds neat throughout the season",
                "Load and transport equipment between job sites",
            ],
        },
        "steps_heading": "Three steps.",
        "steps": [
            ("Enter the basics", "Job title and key requirements, plus department, salary range and a line about your business if you like."),
            ("Get the full posting", "Every section is written and organized for you."),
            ("Post it", "Copy it into any job board, or download it as a PDF."),
        ],
        "callout": None,
        "faqs": [
            ("Where can I post it?", "Anywhere you like &mdash; copy the text into any job board or your own website. The tool writes the description; it doesn't post it for you."),
            ("Can it help with interviews too?", "Yes &mdash; the <a href=\"interview-questions-generator.html\">Hiring Manager</a> tool writes interview questions and a full hiring kit."),
            ("Is what I enter stored?", STORED_WRITING),
        ],
        "cta": "Post your next opening today.",
    },
    # ── Sales & customers ─────────────────────────────────────────────────
    {
        "slug": "proposal-generator.html",
        "app": "business",
        "tool": "Proposal Generator",
        "title": "Proposal &amp; Quote Generator for Small Business",
        "description": "Describe the project and get a professional client proposal: executive summary, scope of work, deliverables, priced line items with a subtotal, and terms.",
        "h1": "Send a proposal that<br><em>looks like you mean business.</em>",
        "lead": "Describe the project, the services and the budget, and get a professional proposal or quote &mdash; executive summary, scope of work, deliverables, priced line items with a subtotal, and terms &mdash; with your business details already on it.",
        "hero_note": "Your business and your client filled in automatically.",
        "outputs_heading": "A complete proposal, ready to send.",
        "outputs_sub": "Everything a client expects to see before they say yes.",
        "outputs": [
            ("Executive summary", "A short opening that explains what you'll do and why it matters to the client."),
            ("Scope of work", "Exactly what's included, so there are no surprises later."),
            ("Deliverables", "What the client gets at the end."),
            ("Priced line items", "A table with quantities, unit prices, totals and a subtotal."),
            ("Terms and validity", "Payment terms, notes and how long the quote is good for."),
            ("Prepared by you, for them", PROFILE + " " + CONTACTS),
        ],
        "example": {
            "heading": "From a project description to a proposal.",
            "sub": "A made-up example, showing part of the line items.",
            "before": "&ldquo;Repaint the interior of a 3-bedroom house: walls and ceilings in all rooms, two coats, client picks colors. Budget around $4,000. About a week.&rdquo;",
            "after_title": "Line items",
            "after": [
                "Surface prep and patching &mdash; 1 &times; $450",
                "Walls, two coats, all rooms &mdash; 1 &times; $2,600",
                "Ceilings, all rooms &mdash; 1 &times; $750",
            ],
        },
        "steps_heading": "Three steps.",
        "steps": [
            ("Describe the project", "What the client needs, plus services, budget range and timeline if you know them."),
            ("Review the proposal", "Check every line item and price &mdash; you know your rates best."),
            ("Send it", "Download it as a PDF and send it to your client."),
        ],
        "callout": "<strong>Check the numbers.</strong> Prices are suggested from the budget you enter. Review every line item before you send it &mdash; the quote goes out under your name.",
        "faqs": [
            ("Will it know my prices?", "Only what you tell it. Enter a budget range and the services you offer, then adjust any line item to your real rates before sending."),
            ("Can I add my business name and logo?", "Your business name and contact details from your business profile are filled in for you. Logos aren't supported yet."),
            ("Is what I enter stored?", STORED_WRITING),
        ],
        "cta": "Win the next job.",
    },
    {
        "slug": "customer-complaint-response.html",
        "app": "business",
        "tool": "Customer Response Drafter",
        "title": "Customer Complaint Response Writer — Reply Calmly and Professionally",
        "description": "Paste a customer's message and get a professional reply in the tone you choose: empathetic, apologetic, firm, friendly or professional. Includes a subject line and a suggested follow-up.",
        "h1": "Answer an angry customer<br><em>without the stress.</em>",
        "lead": "Paste the customer's message, add what happened, and choose a tone. Get a calm, professional reply that addresses every point they raised &mdash; plus a suggested follow-up.",
        "hero_note": "Five tones, from empathetic to firm.",
        "outputs_heading": "The right words when it matters.",
        "outputs_sub": "A reply you can send as-is or adjust in a minute.",
        "outputs": [
            ("A ready-to-send reply", "Written in the tone you pick: professional, empathetic, apologetic, firm or friendly."),
            ("Subject line", "For when you're replying by email."),
            ("Points addressed", "A checklist of each concern the reply covers, so nothing is missed."),
            ("Suggested follow-up", "What to do next to keep the customer."),
            ("Your details, filled in", PROFILE + " " + CONTACTS),
        ],
        "example": {
            "heading": "From a complaint to a reply.",
            "sub": "A made-up example, shortened.",
            "before": "&ldquo;I waited two hours past my appointment window and nobody called. I took the morning off work for this.&rdquo;<br><br>Tone: <strong>Apologetic</strong>",
            "after": "<p class=\"ba-quote\" style=\"font-style:normal;\">&ldquo;I'm sorry &mdash; you took the morning off to meet us, and we didn't show up when we said we would or call to let you know. That's not the service you should expect from us&hellip;&rdquo;</p>",
        },
        "steps_heading": "Three steps.",
        "steps": [
            ("Paste the message", "Add the customer's name and what happened, if you like."),
            ("Choose a tone", "Professional, empathetic, apologetic, firm or friendly."),
            ("Send the reply", "Copy it into your email, text or review reply, so it comes from you."),
        ],
        "callout": None,
        "faqs": [
            ("Will it promise refunds or discounts?", "It works from what you tell it. If you mention a refund or a credit in the context, it can include it. " + REVIEW_IT),
            ("Can I use it for reviews and texts too?", "Yes. Paste any customer message &mdash; an email, a text or an online review &mdash; and copy the reply wherever you need it."),
            ("Is what I enter stored?", STORED_WRITING),
        ],
        "cta": "Turn complaints into second chances.",
    },
    {
        "slug": "review-request-email.html",
        "app": "business",
        "tool": "Review Request Email",
        "title": "Review Request Email Writer — Ask Customers for Google Reviews",
        "description": "Write a friendly, natural email asking a customer to leave a review on Google or another review site, with a subject line and advice on when to send it.",
        "h1": "More reviews start with<br><em>asking the right way.</em>",
        "lead": "Enter your business, the customer and what you did for them, and get a friendly, natural email asking for a review on the sites you choose &mdash; plus advice on when to send it.",
        "hero_note": "Google or any review site you name.",
        "outputs_heading": "An ask that doesn't feel pushy.",
        "outputs_sub": "Personal, short and easy for a happy customer to act on.",
        "outputs": [
            ("Subject line", "One a customer will actually open."),
            ("The email", "Friendly and specific to the work you did for them."),
            ("A spot for your links", "A clear place to paste your review links for each site."),
            ("Timing advice", "When to send it for the best chance of a reply."),
            ("Your details, filled in", PROFILE + " " + CONTACTS),
        ],
        "example": None,
        "steps_heading": "Three steps.",
        "steps": [
            ("Enter the details", "Your business, the customer's name, what you provided and which review sites."),
            ("Add your links", "Paste your Google review link where the email shows."),
            ("Send it", "Copy it into your own email, so it comes from you."),
        ],
        "callout": None,
        "faqs": [
            ("Does it send the emails for me?", "No. Copy it into your own email so it comes from you and your customer recognizes it."),
            ("What are the rules for asking?", "Each site sets its own. Google doesn't allow offering rewards for reviews or asking only happy customers, and Yelp asks businesses not to request reviews at all. Check the rules of any site you use."),
            ("Is what I enter stored?", STORED_WRITING),
        ],
        "cta": "Ask your happiest customers today.",
    },
    # ── Marketing ─────────────────────────────────────────────────────────
    {
        "slug": "social-media-post-generator.html",
        "app": "business",
        "tool": "Social Media Generator",
        "title": "Social Media Post Generator for Small Business",
        "description": "Turn one idea into ready-to-post content for LinkedIn, Instagram, Facebook and more, with hashtags, a suggested time to post and content tips. Pick your tone and goal.",
        "h1": "One idea.<br><em>Posts for every platform.</em>",
        "lead": "Enter a topic, pick your platforms, tone and goal, and get a post written for each platform &mdash; with hashtags, character counts and a suggested time to post.",
        "hero_note": "Five tones and five goals to choose from.",
        "outputs_heading": "Posts that fit each platform.",
        "outputs_sub": "Not the same text pasted everywhere &mdash; each platform gets its own post.",
        "outputs": [
            ("A post per platform", "Written for LinkedIn, Instagram, Facebook, X or whichever platforms you name."),
            ("Hashtags", "Relevant hashtags, shown under each post."),
            ("Best time to post", "A suggested time for each platform."),
            ("Character count", "So you know it fits before you paste it."),
            ("Content tips", "Ideas to get more out of the post."),
            ("Your business, filled in", PROFILE),
        ],
        "example": None,
        "steps_heading": "Three steps.",
        "steps": [
            ("Enter your idea", "A topic, a sale, an event or news &mdash; plus your business name and platforms."),
            ("Pick a tone and goal", "Professional, casual, humorous, inspiring or educational; engagement, awareness, leads, sales or education."),
            ("Post it", "Copy each post into its platform."),
        ],
        "callout": "<strong>Posting is up to you.</strong> The tool writes the posts; it doesn't connect to your accounts or post for you.",
        "faqs": [
            ("Which platforms does it write for?", "Any you name &mdash; LinkedIn, Instagram, Facebook and X are the most common."),
            ("Does it post or schedule for me?", "No. Copy each post into the platform, or into the scheduler you already use."),
            ("Is what I enter stored?", STORED_WRITING),
        ],
        "cta": "Fill your feed this week.",
    },
    {
        "slug": "ad-copy-generator.html",
        "app": "business",
        "tool": "Ad Copy Writer",
        "title": "Ad Copy Generator — Headlines, Descriptions and Calls to Action",
        "description": "Describe your product or service and your audience, pick a goal, and get several headlines, long and short descriptions, call-to-action options and value propositions to test.",
        "h1": "Ad copy you can test,<br><em>not just one guess.</em>",
        "lead": "Describe what you sell, who it's for and what makes it different, pick your goal, and get several headlines, long and short descriptions, call-to-action options and value propositions to mix and test.",
        "hero_note": "Five goals: conversions, awareness, leads, traffic or app installs.",
        "outputs_heading": "Options, not a single draft.",
        "outputs_sub": "Several versions of every piece, so you can test what works.",
        "outputs": [
            ("Headlines", "Several headline options to choose from or test against each other."),
            ("Descriptions", "Longer primary descriptions and short versions for tight spaces."),
            ("Call-to-action options", "Different ways to ask for the click."),
            ("Value propositions", "The reasons to choose you, said clearly."),
            ("Your business, filled in", PROFILE),
            ("Save or send it", TOOLBAR),
        ],
        "example": None,
        "steps_heading": "Three steps.",
        "steps": [
            ("Describe your offer", "Your product or service, your audience and what makes you different."),
            ("Pick a goal", "Conversions, awareness, leads, traffic or app installs."),
            ("Test the options", "Copy your favorite combinations into your ad platform."),
        ],
        "callout": "<strong>Check each platform's limits.</strong> Ad platforms set their own character limits and ad rules, so review each piece before you publish.",
        "faqs": [
            ("Does it run my ads?", "No. It writes the copy; you paste it into Google Ads, Meta or wherever you advertise."),
            ("Can I write social posts too?", "Yes &mdash; that's the <a href=\"social-media-post-generator.html\">Social Media Generator</a>."),
            ("Is what I enter stored?", STORED_WRITING),
        ],
        "cta": "Write your next ad in minutes.",
    },
    # ── Operations ────────────────────────────────────────────────────────
    {
        "slug": "company-policy-generator.html",
        "app": "business",
        "tool": "Policy Generator",
        "title": "Company Policy Generator — Remote Work, PTO, IT and HR Policies",
        "description": "Create a clear, professional company policy in minutes: purpose, scope, organized sections and an employee acknowledgment statement. Remote work, PTO, IT, HR and more.",
        "h1": "Put your rules in writing,<br><em>clearly.</em>",
        "lead": "Name the policy you need &mdash; remote work, PTO, IT use, dress code, anything &mdash; add your industry and any specifics, and get a clear, organized policy document with an acknowledgment for employees to sign.",
        "hero_note": "Any policy type. Have it checked for your state's laws.",
        "outputs_heading": "A complete policy document.",
        "outputs_sub": "Organized the way a policy handbook is.",
        "outputs": [
            ("Purpose and scope", "Why the policy exists and who it covers."),
            ("Organized sections", "Each part of the policy under its own heading."),
            ("Effective date", "A clear spot for the date it takes effect."),
            ("Acknowledgment statement", "A sign-off for employees to confirm they've read it."),
            ("Your business, filled in", PROFILE),
            ("Save or send it", TOOLBAR),
        ],
        "example": None,
        "steps_heading": "Three steps.",
        "steps": [
            ("Name the policy", "For example: Remote Work, PTO, Cell Phone Use, Social Media."),
            ("Add the details", "Your industry and any specific rules you want included."),
            ("Review and share", "Have it checked, then download it as a PDF to share."),
        ],
        "callout": "<strong>Not legal advice.</strong> Employment rules differ by state and industry. Have any policy reviewed by an HR professional or attorney before you put it in place.",
        "faqs": [
            ("What kinds of policies can it write?", "Any you name &mdash; remote work, PTO, IT and computer use, dress code, social media, safety, expenses and more."),
            ("Is it legally compliant?", "It's a well-organized starting draft, not legal advice. Employment law differs by state, so have it reviewed before you use it."),
            ("Is what I enter stored?", STORED_WRITING),
        ],
        "cta": "Write the policy you've been putting off.",
    },
    {
        "slug": "sop-generator.html",
        "app": "business",
        "tool": "SOP Generator",
        "title": "SOP Generator — Write Standard Operating Procedures Step by Step",
        "description": "Describe any business process and get a clear standard operating procedure: purpose, scope, required tools, numbered steps with warnings, and quality checks.",
        "h1": "Get the process<br><em>out of your head.</em>",
        "lead": "Describe how something gets done in your business, and get a clear standard operating procedure &mdash; numbered steps with details and warnings, the tools needed and quality checks &mdash; so it's done right every time.",
        "hero_note": "For any process, daily or once a year.",
        "outputs_heading": "A procedure anyone can follow.",
        "outputs_sub": "Written so someone doing it for the first time can get it right.",
        "outputs": [
            ("Purpose and scope", "What the procedure is for and when it applies."),
            ("How often", "Daily, weekly, per new client &mdash; whatever you enter."),
            ("Required tools", "Everything needed before starting."),
            ("Numbered steps", "Each action with details, and a warning where something can go wrong."),
            ("Quality checks", "How to confirm it was done right."),
            ("Save or send it", TOOLBAR),
        ],
        "example": {
            "heading": "From a description to steps.",
            "sub": "A made-up example, showing the first steps.",
            "before": "Process: <strong>Closing the cafe</strong><br>&ldquo;count the register, clean the espresso machine, put milk away, take out trash, lock up and set the alarm&rdquo;",
            "after_title": "Steps",
            "after": [
                "Count the register and record the total on the closing sheet",
                "Clean the espresso machine &mdash; <em>warning: let the steam wand cool before wiping it</em>",
                "Return all milk and dairy to the walk-in cooler",
            ],
        },
        "steps_heading": "Three steps.",
        "steps": [
            ("Name the process", "Plus the department and how often it happens."),
            ("Describe how it's done", "In your own words, the way you'd explain it to someone new."),
            ("Share the SOP", "Download it as a PDF to print or share."),
        ],
        "callout": None,
        "faqs": [
            ("What's an SOP?", "A standard operating procedure is a written, step-by-step guide for a task, so it's done the same way every time &mdash; whoever does it."),
            ("Can I write company policies too?", "Yes &mdash; that's the <a href=\"company-policy-generator.html\">Policy Generator</a>."),
            ("Is what I enter stored?", STORED_WRITING),
        ],
        "cta": "Document one process today.",
    },
    {
        "slug": "meeting-notes-cleaner.html",
        "app": "business",
        "tool": "Meeting Notes Cleaner",
        "title": "Meeting Notes to Action Items — Clean Up Messy Notes in Seconds",
        "description": "Paste messy meeting notes and get a clean summary with the decisions made, action items with owners and due dates, next steps and a follow-up meeting.",
        "h1": "Messy notes in.<br><em>Action items out.</em>",
        "lead": "Paste your notes from a call or meeting &mdash; typos, fragments and all &mdash; and get a clean summary with the decisions made, who's doing what by when, and the next steps.",
        "hero_note": "Works with notes from any meeting or call.",
        "outputs_heading": "Notes you can actually use.",
        "outputs_sub": "Organized so nothing said in the meeting gets lost.",
        "outputs": [
            ("Summary", "What the meeting was about, in a few sentences."),
            ("Decisions made", "What was agreed, listed clearly."),
            ("Action items", "Each task with an owner and a due date, when your notes mention them."),
            ("Next steps", "What happens after the meeting."),
            ("Follow-up meeting", "When to meet again, if it came up."),
            ("Save or send it", TOOLBAR),
        ],
        "example": {
            "heading": "From scribbles to a summary.",
            "sub": "A made-up example, showing the action items.",
            "before": "&ldquo;call w/ Dana re spring menu - she'll get prices from new supplier by fri, i send photos to printer monday, launch apr 1?? yes agreed&rdquo;",
            "after_title": "Action items",
            "after": [
                "Get prices from the new supplier &mdash; Dana, by Friday",
                "Send menu photos to the printer &mdash; you, Monday",
                "<strong>Decision:</strong> spring menu launches April 1",
            ],
        },
        "steps_heading": "Two steps.",
        "steps": [
            ("Paste your notes", "Add a line about what the meeting was, if you like."),
            ("Share the summary", "Copy it into an email to everyone who was there, or download it as a PDF."),
        ],
        "callout": None,
        "faqs": [
            ("Does it record or join my meetings?", "No. Paste notes you already have &mdash; typed, or copied from a transcript."),
            ("What if my notes don't say who's doing what?", "It only lists what's in your notes. Owners and due dates that weren't mentioned are left for you to fill in."),
            ("Is what I enter stored?", STORED_WRITING),
        ],
        "cta": "Turn your next meeting into a plan.",
    },
    {
        "slug": "business-email-writer.html",
        "app": "business",
        "tool": "Business Email Drafter",
        "title": "Business Email Writer — Professional Emails for Any Situation",
        "description": "Describe what the email is for and who it's to, pick a tone, and get a clear, professional business email with a subject line and a call to action.",
        "h1": "The email you've been<br><em>putting off, written.</em>",
        "lead": "Say what the email is for, who it's going to and the points to cover, pick a tone, and get a clear, professional email with a subject line &mdash; follow-ups, reminders, rescheduling, bad news and more.",
        "hero_note": "Five tones, from friendly to assertive.",
        "outputs_heading": "A clear email in the right tone.",
        "outputs_sub": "Short, professional and easy to send.",
        "outputs": [
            ("Subject line", "Clear about what the email is for."),
            ("The email", "Written in the tone you pick: professional, friendly, formal, assertive or apologetic."),
            ("Call to action", "What you want the reader to do next, stated plainly."),
            ("Your details, filled in", PROFILE + " " + CONTACTS),
            ("Save or send it", TOOLBAR),
        ],
        "example": {
            "heading": "From a purpose to an email.",
            "sub": "A made-up example, shortened.",
            "before": "Purpose: <strong>Payment reminder, invoice 30 days late</strong><br>Tone: <strong>Assertive</strong>",
            "after": "<p class=\"ba-quote\" style=\"font-style:normal;\">&ldquo;Hi Mark, invoice #1042 for $1,850 was due on March 3 and is now 30 days past due. Please send payment by Friday, March 14&hellip;&rdquo;</p>",
        },
        "steps_heading": "Three steps.",
        "steps": [
            ("Describe the email", "What it's for, who it's to and the key points."),
            ("Pick a tone", "Professional, friendly, formal, assertive or apologetic."),
            ("Send it", "Copy it into your email, so it comes from you."),
        ],
        "callout": None,
        "faqs": [
            ("What kinds of emails can it write?", "Anything work-related &mdash; follow-ups, payment reminders, rescheduling, introductions, saying no, delivering bad news and more."),
            ("Will it get the facts right?", "It uses the details you give it. " + REVIEW_IT),
            ("Is what I enter stored?", STORED_WRITING),
        ],
        "cta": "Clear your drafts folder.",
    },
    # ── Data & records ────────────────────────────────────────────────────
    {
        "slug": "small-business-contacts.html",
        "app": "business",
        "tool": "Contacts",
        "title": "Simple Contact Manager for Small Business — Import, Search and Export",
        "description": "Keep clients, vendors and partners in one simple list. Import from your phone, Google Contacts, Outlook or Mac Contacts, search instantly, and export to PDF or vCard.",
        "h1": "All your business contacts.<br><em>One simple list.</em>",
        "lead": "Bring in your contacts from your phone, Google, Outlook or Mac, sort them as clients, vendors, partners or employees, and find anyone in seconds &mdash; then pick them right inside your other Workblox tools.",
        "hero_note": "A lightweight CRM, without the setup.",
        "outputs_heading": "A contact list that works with your tools.",
        "outputs_sub": "Simple enough to use every day.",
        "outputs": [
            ("Import in one step", "Upload a .vcf (vCard) or .csv file from your phone, Google Contacts, Outlook or Mac Contacts."),
            ("Add by hand", "Name, company, type, and as many phones and emails as you need."),
            ("Sort by type", "Client, vendor, partner, employee, personal or other."),
            ("Search instantly", "Find anyone by name, company, phone or email."),
            ("Export", "Save all or selected contacts as a PDF or a vCard file."),
            ("Works with your tools", "Pick a contact inside the Proposal Generator, Customer Response, Review Request and Business Email tools."),
        ],
        "highlight_last": True,
        "example": None,
        "steps_heading": "Three steps.",
        "steps": [
            ("Export from where they are now", "Your phone, Google Contacts, Outlook or Mac Contacts can all save a .vcf or .csv file."),
            ("Import into Workblox", "Upload the file, or add contacts by hand."),
            ("Use them everywhere", "Search, sort and pick contacts inside your other tools."),
        ],
        "callout": None,
        "faqs": [
            ("Is my contact list saved?", "Yes &mdash; Contacts is the one Workblox Business tool that stores data, because it's a contact list. Your contacts are kept with your account. See the <a href=\"privacy.html\">Privacy Policy</a>."),
            ("What happens if I turn the tool off?", "Your contacts aren't deleted. They're waiting for you if you add Contacts back later."),
            ("Can I share contacts with someone else?", "Workblox Business is single-user, so the list is yours. You can export contacts as a PDF or vCard file to share them."),
        ],
        "cta": "Get your contacts in one place.",
    },
    {
        "slug": "spreadsheet-cleaner.html",
        "app": "business",
        "tool": "Spreadsheet Organizer",
        "title": "Spreadsheet Cleaner — Fix Dates, Tidy Text and Remove Duplicates",
        "description": "Upload a messy Excel, CSV or Numbers file and get it back with consistent dates, tidy text and duplicates flagged or merged. Up to 5,000 rows. Nothing is stored.",
        "h1": "Clean up a messy spreadsheet<br><em>in one click.</em>",
        "lead": "Upload an Excel, CSV or Numbers file and get it back with every date in the same format, stray spaces tidied, and duplicate rows flagged for review or merged &mdash; with a before-and-after preview.",
        "hero_note": "Excel, CSV and Numbers. Up to 5,000 rows. Nothing stored.",
        "outputs_heading": "Clean data, same file type.",
        "outputs_sub": "You get back the same kind of file you uploaded, cleaned.",
        "outputs": [
            ("Consistent dates", "Every date in one format &mdash; detected automatically, or MM-DD-YYYY or DD-MM-YYYY."),
            ("Tidy text", "Extra spaces and messy cells cleaned up."),
            ("Duplicates handled", "Flag duplicate rows for you to review, or merge exact matches automatically."),
            ("Problems flagged", "Dates that are unclear or unreadable are marked for you to check, not guessed."),
            ("Before and after", "A preview and a summary of every change before you download."),
            ("Same file type back", "Upload Excel, CSV or Numbers and download the cleaned file in that format."),
        ],
        "example": None,
        "steps_heading": "Three steps.",
        "steps": [
            ("Upload your file", "Excel (.xlsx), CSV or Numbers, up to 5,000 rows. Say what the data is, if you like."),
            ("Choose your options", "Date format and how to handle duplicates."),
            ("Download the clean file", "Check the before-and-after preview, then download."),
        ],
        "callout": None,
        "faqs": [
            ("Will it change my numbers or names?", "It standardizes dates and tidies text. It doesn't rewrite your data &mdash; and it flags what it isn't sure about instead of guessing."),
            ("How big a file can it handle?", "Up to 5,000 rows per file."),
            ("Is my file stored?", STORED_FILES),
        ],
        "cta": "Fix your spreadsheet now.",
    },
    {
        "slug": "receipt-expense-organizer.html",
        "app": "business",
        "tool": "Expense Organizer",
        "title": "Receipt &amp; Expense Organizer — Turn Receipts Into a Categorized Spreadsheet",
        "description": "Upload receipt photos and bank or card exports and get a categorized expense table with totals you can edit and export to Excel or Numbers. Nothing is stored.",
        "h1": "Shoebox of receipts?<br><em>Spreadsheet in minutes.</em>",
        "lead": "Upload photos of receipts and your bank or card exports, and get one categorized expense table &mdash; date, vendor, amount and category, with totals &mdash; that you can correct and export to a spreadsheet.",
        "hero_note": "Photos, PDFs and bank exports. Nothing stored.",
        "outputs_heading": "Your expenses, sorted.",
        "outputs_sub": "Ready for your bookkeeper, your taxes or your own records.",
        "outputs": [
            ("Receipts read for you", "The date, vendor and total are read from each receipt photo or PDF."),
            ("Bank exports cleaned up", "Cryptic card descriptions turned into readable vendor names."),
            ("Categories", "Meals, travel, software, supplies and more &mdash; or your own categories."),
            ("Anything unclear flagged", "Unreadable or uncertain entries are marked &ldquo;Check this&rdquo; instead of guessed."),
            ("Totals", "A total for each category and a grand total."),
            ("Edit and export", "Correct any cell, then export to Excel, or Numbers if that's what you use."),
        ],
        "example": None,
        "steps_heading": "Three steps.",
        "steps": [
            ("Upload up to 10 files", "Receipt photos (JPG, PNG, HEIC), PDFs, and bank or card exports (CSV, Excel, Numbers)."),
            ("Pick a date range", "This month, last month, a custom range or all dates."),
            ("Review and export", "Fix anything marked &ldquo;Check this,&rdquo; then export your spreadsheet."),
        ],
        "callout": "<strong>Not tax advice.</strong> Categories help you organize. Your accountant decides what's deductible.",
        "faqs": [
            ("What files can I upload?", "Up to 10 at a time: receipt photos (JPG, PNG, HEIC), PDFs, and bank or credit card exports as CSV, Excel or Numbers files."),
            ("Can I use my own categories?", "Yes. Enter your own, separated by commas, or use the built-in list: Meals, Travel, Lodging, Office Supplies, Software, Utilities, Professional Services, Marketing, Equipment and Other."),
            ("Are my receipts stored?", STORED_FILES),
        ],
        "cta": "Get your expenses organized.",
    },
]
